<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <LangVersion>10</LangVersion>
	  <Version>7.26.2901</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.148.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.148.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CaptchaCodeRenderer_system_drawing.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IdentityServerNET\IdentityServerNET.csproj" />
  </ItemGroup>

</Project>
