@hostname=localhost
# @port=44300
@port=60602

POST https://{{hostname}}:{{port}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=is-net-webapi-commands&client_secret=secret&scope=is-net-webapi is-net-webapi.command

###

POST https://{{hostname}}:{{port}}/connect/token
Authorization: Basic bXktYXBpLWNvbW1hbmRzOnNlY3JldA==
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=is-net-webapi is-net-webapi.command

###

@api_hostname=localhost
@api_port=60889

GET https://{{api_hostname}}:{{api_port}}/identity
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU2ODA3NEE1OTk4Q0IxOTE2QTU0RThCQUQ2QkZEMjQzMDg4NTgzRkRSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6IlZvQjBwWm1Nc1pGcVZPaTYxcl9TUXdpRmdfMCJ9.eyJuYmYiOjE3ODIyOTc3OTYsImV4cCI6MTc4MjMwMTM5NiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NjA2MDIiLCJhdWQiOiJpcy1ub3ZhLXdlYmFwaSIsImNsaWVudF9pZCI6ImlzLW5vdmEtd2ViYXBpLWNvbW1hbmRzIiwianRpIjoiRTY2MTUwRDVDOUQ1MjhBMUE2NUNDQTlEQkYzOUEwNkUiLCJpYXQiOjE3ODIyOTc3OTYsInNjb3BlIjpbImlzLW5vdmEtd2ViYXBpIiwiaXMtbm92YS13ZWJhcGkuY29tbWFuZCJdfQ.s8mLZv3Illjst_ZpVSuxkjK1LSZdXM5vFUeJ4Ol_YV843OxWqlJ8iustl2b48936PrqsJJ9b2t9EGkbOp_GiqXndGKr2si-3Lv0Q2qpRc1Q10vBot3kl7AKSwmaclas-KwGi_5PsC4xRtwQhuVFHZjmrjRtdkanyIhfXskm-mDti0f0_XAsrLjquvOvXZfucnxMFMz2nYMlQmQ-peYV1P4995eR-xs-ffRSqw608_LEO20-0He22-ZSNSKiE2fqtVwpZRd8i3VqmKvppJQjTFhPCvHOkknP-fVASfGb3_bnQwhr7xOyymEs1zRgmOVvwyb6qdWTOmOTMbStPhLqQdw