<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
	  <Version>7.26.2701</Version>
	  <Copyright>2026, Jürgen Gstaltmaier</Copyright>
	  <PackageProjectUrl>https://github.com/jugstalt/identityservernet</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/jugstalt/identityservernet</RepositoryUrl>
	  <Authors>Jürgen Gstaltmaier</Authors>
	  <Company />
	  <Product />
	  <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	  <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
